### ISSUE TITLE
Update `c_type_byte_size` calls to `cTypeByteSize` for Zig 0.14.0

### ISSUE THREAD

**Issue by yhyadev** [vezel-dev/libffi#7]
It is used in

https://github.com/vezel-dev/libffi/blob/9270e462b9cc7293ed1978e4bdeff7337e6fd6e0/build.zig#L251

And

https://github.com/vezel-dev/libffi/blob/9270e462b9cc7293ed1978e4bdeff7337e6fd6e0/build.zig#L252

**Comment by alexrp** [comment]
Done in `master`; not yet in a release.
